# Generated by Django 2.1.3 on 2018-12-09 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caderno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dta_origem', models.DateField(auto_now_add=True, verbose_name='data origem')),
                ('dta_mod', models.DateField(auto_now=True, verbose_name='data modificação')),
                ('nome', models.CharField(max_length=100)),
                ('favorito', models.BooleanField(default=False)),
                ('usu_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caderno_modificado', to=settings.AUTH_USER_MODEL)),
                ('usu_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caderno_criado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dta_origem', models.DateField(auto_now_add=True, verbose_name='data origem')),
                ('dta_mod', models.DateField(auto_now=True, verbose_name='data modificação')),
                ('nome', models.CharField(max_length=100)),
                ('usu_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta_criado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dta_origem', models.DateField(auto_now_add=True, verbose_name='data origem')),
                ('dta_mod', models.DateField(auto_now=True, verbose_name='data modificação')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('etiquetas', models.ManyToManyField(blank=True, null=True, to='anotacao.Etiqueta')),
                ('usu_mod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_modificado', to=settings.AUTH_USER_MODEL)),
                ('usu_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_criado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='etiqueta',
            unique_together={('nome', 'usu_origem')},
        ),
        migrations.AlterUniqueTogether(
            name='caderno',
            unique_together={('nome', 'usu_origem')},
        ),
    ]
