# Generated by Django 2.1.3 on 2018-12-09 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anotacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caderno',
            name='usu_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caderno_modificado', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por'),
        ),
        migrations.AlterField(
            model_name='caderno',
            name='usu_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caderno_criado', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='usu_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiqueta_criado', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='usu_mod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_modificado', to=settings.AUTH_USER_MODEL, verbose_name='Modificado Por'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='usu_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_criado', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por'),
        ),
    ]
